Frech Translation
libreobjet/open-guide pull request #22
Opened 2018-03-06 11:17 UTC by sintoniz

FILES
introduction.md
motivation.md

This is about the request for help for the translation into French
https://github.com/libreobjet/open-guide/issues/14

NOTE:
I still have some doubts about how github works, so I hope that the process I'm doing is correct ;-)

2018-03-06 16:52 UTC, xuv commented
Bonjour @sintoniz, merci pour cette proposition et pour ton travail. Je lis les traductions que tu proposes et je trouve certaines tournures de phrases un petit peu alambiquées. Il me semble que tu t'es servi d'un logiciel de traduction automatique. 
Cela ne me pose pas de problèmes que tu utilises cela, mais je trouverais cela plus lisible si tu corrigeais les  phrases par après.
Dis moi ce que tu en penses.

2018-03-07 11:29 UTC, sintoniz commented
The hard work in translating this project is the part of the edition marks that are in the text and the references to authors, documents and projects which requires a very exhaustive supervision if automatic translation is used. Everyone uses it as a tool for a matter of performance as we use the computer instead of pencil and paper. You can be sure that I have carried out that supervision with total honesty.

I concentrate on making the translation understandable although, of course, it can be improved. I believe that translating is an onion-shaped process, in which each layer subtly improves the previous one.

:-)
Je tiens seulement à ajouter que j'apprécie grandement tout propriétaire de projet qui veille soigneusement à ce que les contributions aient une qualité acceptable.

2018-03-07 16:36 UTC, xuv requested changes
Beaucoup d'éléments dans ce texte nécessitent une ré-écriture afin de produire un texte agréable à lire en Français. Certains éléments ont été pointés dans cette page. Mais beaucoup d'autres paragraphes ont besoin d'une attention similaire. Merci d'avance de prendre cela en compte.

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +Si le profit est le rapport d'or des histoires de réussite et le prisme à travers lequel le design devrait être pensé aujourd'hui, alors ce que nous nous retrouvons avec:
@sintoniz Cette phrase-ci est particulièrement étrange à lire et sonne comme une traduction mot pour mots de l'anglais. Malheureusement, ça ne veut plus dire grand chose en Français. Serait-il possible de l'améliorer?

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +Ce que nous apprenons dans la plupart des écoles de design, c'est de protéger notre travail en utilisant des brevets et des droits liés au design industriel (dépôts de modèles et de dessins, etc.). I
@sintoniz La seconde partie de cette phrase est aussi un peu étrange à lire. On dirait qu'elle manque de quelques mots pour lier le tout.

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +Dont l'obsolescence planifiée maintenant célèbre avec la seule intention d'augmenter le volume des ventes et de produire des ordures.
@sintoniz À revoir.

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +Il y a beaucoup de débat autour de la copie et de ses connotations généralement négatives. Il existe des «copies illégales» qui pourraient vous nuire, vous ou l'auteur, le contrôle délirant des copie
@sintoniz Ici, je corrigerais le verbe "demandez" en "demande" et je dirais "à cause de l'industrie du divertissement".

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +Ok, c'est difficile. Quels sont les outils pour rester motivé ou pour vous motiver à aller dans la conception de produits open source? C'est en fait une question très personnelle. Nous espérons que c
@sintoniz Paragraphe à revoir.

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +### Défiez-vous
@sintoniz À mon avis le titre n'est pas idéal ici.

2018-03-07 16:36 UTC, xuv commented on fr/motivation.md
> +### Libérez tôt, relâchez souvent
@sintoniz Il faut trouver une autre formule pour ce titre.

2018-04-02 16:11 UTC, xuv commented
This was apparently part of an abuse of Utopian platform. So closing it. More info in this article: https://steemit.com/utopian-io/@xuv/utopian-io-is-breaking-the-open-source-contribution-model-and-needs-to-be-fixed

2018-04-02 16:11 UTC, closed without merging